
# ====================================#
# Things you should definitely change # 
# ====================================#

# Name for this genotyping effort
# This will be the basename of the output VCF file (i.e. you don't need the .vcf.gz suffix).
project_name: "you_should_read_the_config_file"

# Path to a comma-separated sample sheet with columns:
# 1. sample name
# 2. paths to fastq files for mate pair 1.
# 3. paths to fastq files for mate pair 2.
sample_sheet: "/groups/nordborg/projects/crosses/tom/02_library/mpileup_call_pipeline/test_data/test_sample_sheet.csv"


# =============================== #
# Things you might want to change #
# =============================== #

# Path to a reference genome to align reads to.
fasta: "/groups/nordborg/common_data/TAIR10/TAIR10_chromosome_files/TAIR10_chr_all.fas"

# Path to a 'targets file' giving the positions of known SNP positions.
# This should be formatted as a file that can be passed to the argument -T or 
# --targets-file in bcftools
# See https://samtools.github.io/bcftools/bcftools.html#common_options.
targets: "/groups/nordborg/common_data/fernandos_SNP_calls/1163g.179kB.prior15.gauss4.ts99.5.BIALLELIC.targets_file.tsv.gz"

# ============================= #
# Things you can probably leave #
# ============================= #

# Settings for trim galore.
trim_galore:
  clip_R1: 15
  clip_R2: 15
  quality: 20 # Minimum quality score to trim ends
  length: 20 # Minimum read length

# Settings 
mpileup:
  max_depth: 10000 # Maximum total coverage allowed at a site across samples. median coverage x sample size x 4.
  min_MQ: 20
  min_BQ: 20