name: mpileup_call_pipeline
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python >=3.10
  - pandas
  - snakemake
  - snakemake-executor-plugin-slurm
  - bcftools
  - bwa
  - multiqc
  - samtools
  - trim-galore